services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  WapplerSystems\FormEnd2End\:
    resource: '../Classes/*'

  WapplerSystems\FormEnd2End\Powermail\EventListener\SendMailServicePrepareAndSendEventListener:
    tags:
      - name: event.listener
        method: __invoke
        identifier: 'wapplersystems-form-e2e/send-mail-service-prepare-and-send'

