services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  WapplerSystems\MailEnd2End\:
    resource: '../Classes/*'

  WapplerSystems\MailEnd2End\Powermail\EventListener\ReceiverMailReceiverPropertiesServiceSetReceiverEmailsEventListener:
    tags:
      - name: event.listener
        method: __invoke
        identifier: 'wapplersystems-mail-e2e/receiver-mail-receiver-properties-service-set-receiver-emails'
